### ISSUE TITLE
pnpm dev error

### ISSUE THREAD

**Issue by unnimona** [viandwi24/nuxt3-awesome-starter#32]
pnpm install

 ERROR  Failed to resolve import "ufo" from "virtual:nuxt:/home/juno/Downloads/nuxt3-awesome-starter/.nuxt/paths.mjs". Does the file exist?        03:20:57

 ERROR  Failed to resolve import "defu" from ".nuxt/app.config.mjs". Does the file exist?                                                          03:21:00

✔ Nitro built in 1938 ms                                                                                             

500
[vite-node] Failed to load ufo

at ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@0.23.4_sass@1.53.0/node_modules/vite-node/dist/client.mjs:180:13)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ViteNodeRunner.cachedRequest (./node_modules/.pnpm/vite-node@0.23.4_sass@1.53.0/node_modules/vite-node/dist/client.mjs:128:12)
at async request (./node_modules/.pnpm/vite-node@0.23.4_sass@1.53.0/node_modules/vite-node/dist/client.mjs:151:16)
at async virtual:nuxt:./.nuxt/paths.mjs:1:238
at async ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@0.23.4_sass@1.53.0/node_modules/vite-node/dist/client.mjs:251:5)
at async ViteNodeRunner.cachedRequest (./node_modules/.pnpm/vite-node@0.23.4_sass@1.53.0/node_modules/vite-node/dist/client.mjs:128:12)
at async request (./node_modules/.pnpm/vite-node@0.23.4_sass@1.53.0/node_modules/vite-node/dist/client.mjs:151:16)
at async ./node_modules/.pnpm/nuxt3@3.0.0-rc.12-27730995.2894a75_3qgq5m7bqj7palvvc4uezrk4iq/node_modules/nuxt3/dist/app/entry.mjs:5:31
at async ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@0.23.4_sass@1.53.0/node_modules/vite-node/dist/client.mjs:251:5)

**Comment by viandwi24** [comment]
after u clone this repo, have u run the following command like this "pnpm install --shamefully-hoist" ??
or u just "pnpm install" ?

**Comment by unnimona** [comment]
cool that works
