### ISSUE TITLE
ERROR  No "exports" main defined in /Users/****/node_modules/@nuxt/kit/package.json 

### ISSUE THREAD

**Issue by zanedeng** [viandwi24/nuxt3-awesome-starter#55]
Installing any dependencies will report the following error, please advise

```
 ERROR  No "exports" main defined in /Users/****/node_modules/@nuxt/kit/package.json                        21:45:18

  at new NodeError (node:internal/errors:393:5)
  at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
  at packageExportsResolve (node:internal/modules/esm/resolve:612:7)
  at resolveExports (node:internal/modules/cjs/loader:529:36)
  at Module._findPath (node:internal/modules/cjs/loader:569:31)
  at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)                                                    21:45:18
  at Function.resolve (node:internal/modules/cjs/helpers:109:19)
  at resolveModule (node_modules/.pnpm/nuxi@3.1.1/node_modules/nuxi/dist/shared/nuxi.f17c7643.mjs:17:29)
  at importModule (node_modules/.pnpm/nuxi@3.1.1/node_modules/nuxi/dist/shared/nuxi.f17c7643.mjs:37:24)
  at loadKit (node_modules/.pnpm/nuxi@3.1.1/node_modules/nuxi/dist/shared/nuxi.ede95f37.mjs:5:18)
```

**Comment by parhelium** [comment]
Confirm having the same issue...

**Comment by zanedeng** [comment]
Need to upgrade nuxt to the latest version
`pnpm update nuxt@3.3.1`

**Comment by LokerL** [comment]
> Need to upgrade nuxt to the latest version `pnpm update nuxt@3.3.1`

 Cannot start nuxt:  Nuxt instance is unavailable!
