### ISSUE TITLE
[unhandledRejection] Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by cnelf** [viandwi24/nuxt3-awesome-starter#57]
When I execute `npm run dev`, Command line has an error.

![image](https://user-images.githubusercontent.com/42031617/226860692-35118754-442c-4249-b173-cb034eae26d2.png)

Environment
```
- Node Version:     `16.18.1`
```

Describe the bug
```
 ERROR  [unhandledRejection] Cannot set headers after they are sent to the client            17:33:19

  at new NodeError (node:internal/errors:387:5)
  at ServerResponse.setHeader (node:_http_outgoing:644:11)
  at sendError (/D:/Workplace/nuxt3-starter/node_modules/.pnpm/h3@1.1.0/node_modules/h3/dist/index.mjs:189:18)
  at Server.toNodeHandle (/D:/Workplace/nuxt3-starter/node_modules/.pnpm/h3@1.1.0/node_modules/h3/dist/index.mjs:927:15)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by xkloveme** [comment]
me to...

**Comment by Dev-A-Line** [comment]
Me to...
![image](https://user-images.githubusercontent.com/14335460/232287712-93c163a3-0c52-495b-91f2-301c14334e17.png)

**Comment by adronitis** [comment]
@cnelf I had the same issue with node v16.x but seems like if you switch to node v18, this error will be gone.

**Comment by Dev-A-Line** [comment]
> @cnelf I had the same issue with node v16.x but seems like if you switch to node v18, this error will be gone.

Hello, could you please tell me how to do this correctly?

**Comment by adronitis** [comment]
@Dev-A-Line You could install https://github.com/nvm-sh/nvm and switch to a different node version easily.

**Comment by Dev-A-Line** [comment]
> @Dev-A-Line You could install https://github.com/nvm-sh/nvm and switch to a different node version easily.

Strange put 18.16.0 and it still stays, did you do something else ? 

![image](https://user-images.githubusercontent.com/14335460/232477094-c5f3aa9b-3763-4ef8-b5fd-bfe316416bdf.png)

**Comment by viandwi24** [comment]
is problem still exist?

**Comment by cnelf** [comment]
> is problem still exist?

This issue seems to be non-existent on macOS. I'm running fine on macOS or Windows sym with Node v18.x environment.
